:apiVersion: route.openshift.io/v1                                         
kind: Route                                                               
metadata:                                                                 
  name: simon-argocd                                                        
  labels:                                                                 
    app: simon-argocd                                                       
spec:
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /spec/host
    - /status 
