apiVersion: v1
kind: Service                                                             
imetadata:                                                                 
  name: simon-argocd
  labels:
    app: simon-argocd
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: simon-argocd
